### PR TITLE
Fix ignored service annotations

### PR DESCRIPTION
**Pull request by jpoisso**
The issue identified was caused by an 'if' statement on the mancenter's service annotations instead of the hazelcast's service itself, which lead to ignored annotations from values.yaml.

The bug affected both hazelcast and hazelcast-enterprise charts.

Effective changes:

{{- if .Values.mancenter.service.annotations }}

becomes 

{{- if .Values.service.annotations }}

### CODE REVIEW

**Comment by hasancelik** [comment]
Hi @jpoisso, Thanks for the PR. Could you please bump up the chart version in `chart.yaml` (for both `hazelcast` and `hazelcast-enterprise`)?

**Comment by jpoisso** [comment]
> Hi @jpoisso, Thanks for the PR. Could you please bump up the chart version in `chart.yaml` (for both `hazelcast` and `hazelcast-enterprise`)?

Done. I bumped it up to 5.1.1 as this seemed like a bugfix but if you prefer 5.2.0, I can change it.

**Comment by SeriyBg** [comment]
verify

**Comment by SeriyBg** [comment]
> > Hi @jpoisso, Thanks for the PR. Could you please bump up the chart version in `chart.yaml` (for both `hazelcast` and `hazelcast-enterprise`)?
> 
> Done. I bumped it up to 5.2.0

Hi @jpoisso, it seems that 5.2.0 is already the master version. Could you please bump it up once again? Sorry for the inconveniences

**Comment by SeriyBg** [comment]
verify

**Pull request merged**
