### PR TITLE
expose hazelcast service annotations

### LINKED ISSUE #199: expose service annotations
Right now I have to use a post-install helm hook and wrap the chart to do this, so it would be great if this was exposed by default as seems to be the norm.

two use cases:
* setting external dns name annotation
* setting IP pool annotation

typical way is something like this in the values.yaml:
```yaml
service:
  type: LoadBalancer
  annotations: {}
```

and then the person deploying can decide to annotate or not.

### PR DESCRIPTION
**Pull request by justinrush**
exposes hazelcast service annotations in values.yaml

closes #199

### CODE REVIEW

**Review by hasancelik — CHANGES_REQUESTED** [review]
@justinrush Thanks a lot for your PR 👍 

Could you make same changes for `hazelcast-enterprise` chart as well?
https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise

Could you bump up chart versions?
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/Chart.yaml#L3
https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/Chart.yaml#L3

**Comment by hasancelik** [comment]
@justinrush Could you sign CLA as well?

**Comment by justinrush** [comment]
> @justinrush Could you sign CLA as well?

I'm not sure yet, waiting on review. Likely would not have made PR had I seen there was a CLA. You should have a CONTRIBUTING.md at the root of the project clearly indicting you want people to sign one.

**Comment by hasancelik** [comment]
@justinrush you are right, we need to inform our contributors about this kind of things. I have already created [PR](https://github.com/hazelcast/charts/pull/201) for it, thanks for the reminder 👍 

If you have any question or concern about our CLA itself, I can try to clarify your points with the help of our legal team :)

**Comment by justinrush** [comment]
> @justinrush Thanks a lot for your PR 👍
> 
> Could you make same changes for `hazelcast-enterprise` chart as well?
> https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise
> 
> Could you bump up chart versions?
> https://github.com/hazelcast/charts/blob/master/stable/hazelcast/Chart.yaml#L3
> https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/Chart.yaml#L3

This is done and the CLA is signed - should be good to go. Let me know if you want anything else done for this one.

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
Hey @justinrush, 

Thanks for the updates.

It seems there is an issue about you CLA signing. My guess is, the problem is in the mismatch of the email addressed assigned on your GH account and in the Git commit email. We have seen this before, the emails have to match.
The usual solution is to amend the commits and set the email that is assigned to your GH account.

**Comment by justinrush** [comment]
> Hey @justinrush,
> 
> Thanks for the updates.
> 
> It seems there is an issue about you CLA signing. My guess is, the problem is in the mismatch of the email addressed assigned on your GH account and in the Git commit email. We have seen this before, the emails have to match.
> The usual solution is to amend the commits and set the email that is assigned to your GH account.

I think that fixed it?

**Review by hasancelik — APPROVED** [review]

**Pull request merged**
