### PR TITLE
use ct(chart-testing) tool for helm charts

### PR DESCRIPTION
**Pull request by hasancelik**
`ct` tool is maintained by `helm` --> https://github.com/helm/chart-testing. With this tool, our pr-builder can check/compare chart version as well:
```
Linting chart 'hazelcast => (version: "3.0.6", path: "stable/hazelcast")'
Checking chart 'hazelcast => (version: "3.0.6", path: "stable/hazelcast")' for a version bump...
Old chart version: 3.0.5
New chart version: 3.0.6
Chart version ok.
Validating /home/jenkins/jenkins_slave/workspace/helm-charts-os-pr-builder-test/stable/hazelcast/Chart.yaml...
Validation success! 👍
```
I have already updated existing PR builder based on changes at the PR so you can check improvements directly from first PR builder run of the PR.

### CODE REVIEW

**Comment by hasancelik** [comment]
First run failed due to chart version 🙂:
```
17:15:33 Linting chart 'hazelcast-jet => (version: "1.4.2", path: "stable/hazelcast-jet")'
17:15:33 Checking chart 'hazelcast-jet => (version: "1.4.2", path: "stable/hazelcast-jet")' for a version bump...
17:15:33 Old chart version: 1.4.2
17:15:33 New chart version: 1.4.2
17:15:33 Linting chart 'hazelcast => (version: "3.0.5", path: "stable/hazelcast")'
17:15:33 Checking chart 'hazelcast => (version: "3.0.5", path: "stable/hazelcast")' for a version bump...
17:15:33 Old chart version: 3.0.5
17:15:33 New chart version: 3.0.5
17:15:33 Error: Error linting and installing charts: Error processing charts
```
 http://jenkins.hazelcast.com/view/Plugins/job/helm-charts-os-pr-builder/124/console

**Comment by eminn** [comment]
Can we configure an enterprise key the same way we've configure the GKE tokens and include the enterprise tests as well ?

**Comment by hasancelik** [comment]
> Can we configure an enterprise key the same way we've configure the GKE tokens and include the enterprise tests as well ?

Done, check the latest commit 👍

**Comment by hasancelik** [comment]
verify

**Pull request merged**
