### PR TITLE
Additional Environment Variables

### PR DESCRIPTION
**Pull request by sprehn**
Resolves: #236

This PR adds the ability to define additional custom environment variables.

### CODE REVIEW

**Review by leszko — COMMENTED** [review]
Hi Sebastian, thanks for your PR. Could you add the same change to the hazelcast-enterprise chart? Also, please bump up the chart version in `chart.yaml` (for both `hazelcast` and `hazelcast-enterprise`)?

**Review by leszko — COMMENTED** [review]
@sprehn could you also bump the chart version in `hazelcast-enterprise/chart.yaml`?

**Comment by sprehn** [comment]
Sorry, think I missed to add the file to the commit. Done now.

**Review by leszko — APPROVED** [review]
Thanks @sprehn

**Pull request merged**
