### PR TITLE
converted markdown files for Hazelcast and hazelcast jet enterprise editions to asciidoc

### PR DESCRIPTION
**Pull request by sjha2048**
Converted  EE READMEs to adoc format 

Fixes: #72
Signed-off-by: sahil <sjha200000@gmail.com>

### CODE REVIEW

**Comment by hasancelik** [comment]
@sjha2048  Could I ask you to sign our Contributor's agreement to merge your PR?
https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

**Comment by sjha2048** [comment]
Sure thing!

**Comment by hasancelik** [comment]
Hi @sjha2048, little reminder --> We need the CLA signed. We're looking forward to your contribution 👍

**Comment by sjha2048** [comment]
Hello, sorry for the late reply actually I don't own a printer and my city is currently in lockdown so can I sign it digitally?

**Comment by hasancelik** [comment]
> Hello, sorry for the late reply actually I don't own a printer and my city is currently in lockdown so can I sign it digitally?

@sjha2048 You can fill and sign the CLA doc/pdf via proper editor 👍 btw, I know, it's a complicated process, we're working on a better solution.

**Comment by sjha2048** [comment]
done @hasancelik

**Comment by hasancelik** [comment]
Thanks @sjha2048 

Could you resolve merge conflicts and bump up the Chart versions again? I have merged some PRs that updates Chart versions while waiting your document 🙂

**Comment by sjha2048** [comment]
I tried checking out pull request locally then also I am not able to see these conflicts locally, git status also doesn't show conflicts, maybe I am missing something can you help me out?

**Comment by hasancelik** [comment]
> I tried checking out pull request locally then also I am not able to see these conflicts locally, git status also doesn't show conflicts, maybe I am missing something can you help me out?

Could you first pull latest changes into your `master` branch then try to rebase your `fix/md_to_adoc` with master?

**Comment by sjha2048** [comment]
Still facing the same issue, shall I open a new pr, I know this is not the
best practice but if you don't have any issues with it then please let me
know.

**Comment by hasancelik** [comment]
it is very strange anyway creating new PR is not issue for us, you can create new one and assign me as reviewer. Thanks for your concern 👍

**Pull request closed without merging**
