### PR TITLE
[mancenter] adding ingressClassName to select ingress controller

### PR DESCRIPTION
**Pull request by sandromodarelli**
Hello team,
in this PR you will find a little improvement: select the ingress controller to expose mancenter

I also bumped the chart version to new minor one.

Feedback always welcome :pray:

### CODE REVIEW

**Comment by yunussandikci** [comment]
Hi @hasancelik 👋, 
Could you please review or help us to point out who can check this PR of my colleague? 🙂
Thank you in advance!

**Review by hasancelik — APPROVED** [review]

**Comment by hasancelik** [comment]
Hi @yunussandikci, 

Of course 🙂 

Hi @sandromodarelli Thanks for the PR 👍

**Comment by mtyazici** [comment]
Hi @sandromodarelli, 

Thank you for the PR. I noticed that we are already using `networking.k8s.io/v1` which was introduced in k8s `v1.19`. I believe we don't need to put k8s version specific checks into the Ingress file since we know that k8s version is greater than `v1.19`. However, I think we should bump the `kubeVersion` in `Chart.yaml` into `>=1.19.0-0`, and directly take `.Values.mancenter.ingress.className` and put it into ingress spec if it is not empty.

Also, could you please add the same changes for `hazelcast-enterprise` chart and bump the Chart versions again?

**Comment by sandromodarelli** [comment]
@mtyazici PR improved following your suggestions. please, review when you can :pray:

**Comment by mtyazici** [comment]
Thanks again @sandromodarelli, LGTM 👍🏼

I see that the version is the same between main and this branch. There was probably a PR merged after this one was opened. Could you please bump the versions again for both charts?

**Comment by sandromodarelli** [comment]
thank you @mtyazici . both charts' versions bumped

**Review by mtyazici — APPROVED** [review]

**Pull request merged**
