### PR TITLE
Add runAsGroup in SecurityContext

### LINKED ISSUE #41: Add `runAsGroup`
By default the Pod uses the group 0 (root). We could add the parameter `runAsGroup` (as reported by @mesutcelik in #38 ).

### PR DESCRIPTION
**Pull request by cristina-sirbu**
This PR should fix #41.

### CODE REVIEW

**Comment by Holmistr** [comment]
verify

**Comment by mesutcelik** [comment]
@cristina-sirbu Thanks for the PR!
Can you please update README files too?

Have you been able to verify those changes locally or in a cloud based kubernetes cluster?
You can use a hosted kubernetes cluster(i.e. GKE) or minikube to test locally. 

Let me know if you need any help.

**Comment by cristina-sirbu** [comment]
Hello @mesutcelik! I updated the ReadMe and added a comment in the values files to mention what this _runAsGroup_ property does. 
I tested my fix locally using the Kubernetes cluster that comes with Docker for Desktop. I installed the hazelcast helm chart with the default settings (`helm install hazelcast/hazelcast`) and with my changes from local sources (`helm install .`) and set runAsGroup to 50000 in the values file. And I've done `kubectl exec -it illmannered-ocelot-hazelcast-0 -- sh` into all pods that get created. Then I've run `id` into those pods. In the official helm chart the result of the `id` command is:
`uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)`
And in helm chart that contains my changes is:
`uid=65534(nobody) gid=50000 groups=65534(nobody)`
I've followed the official [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
Anything else I can do for this issue?

**Comment by Holmistr** [comment]
Hey @cristina-sirbu , looks like this PR is going in the right direction and getting close to finish. Awesome! :tada: Let's wait for one more round of reviews.

In the meantime, could I ask you to sign our Contributor's agreement?
https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

**Comment by cristina-sirbu** [comment]
@Holmistr Done. Signed and sent. 👍

**Comment by Holmistr** [comment]
@cristina-sirbu Fantastic, thanks. I can confirm that we received it. So the only missing piece are the reviews, which will be provided soon. Thank you very much for your interest! :+1:

**Comment by hasancelik** [comment]
@cristina-sirbu,  I want to also inform you about our pipeline. When your PR merged, [create-pr-at-official-helm-repo](https://github.com/hazelcast/charts/blob/master/create-pr-at-official-helm-repo) script copy will your changes to [helm/charts](https://github.com/helm/charts) repo automatically via using `devOpsHelm` github user. Here is the sample auto-generated PR:
https://github.com/helm/charts/pull/20762

- If you are ok with the process, you don't need do anything.
- If you are not, you can create another PR at [helm/charts](https://github.com/helm/charts) after your existing PR merged. But before, to avoid/disable [create-pr-at-official-helm-repo](https://github.com/hazelcast/charts/blob/master/create-pr-at-official-helm-repo) script, you need squash your all commits and add `[not-sync]` phrase into commit message. You can find  sample `[not-sync]` commit, [here](https://github.com/hazelcast/charts/commit/59d0d271c5e4df35db27cf6ee5ca34a1c38f05be)

**Comment by mesutcelik** [comment]
@cristina-sirbu Can you please update all 4 READMEs? I see only one of them updated.

**Comment by cristina-sirbu** [comment]
@mesutcelik Thank you for noticing that! I got lost a bit 😄 
@hasancelik Bumped the Chart version for all four charts. And I am happy with the automated process to push the helm chart to the official repo. 👍

**Comment by mesutcelik** [comment]
@cristina-sirbu 🎉Thanks for the contribution!

**Comment by hasancelik** [comment]
@cristina-sirbu Here is the auto-generated PRs at official helm repo:
https://github.com/helm/charts/pull/21173
https://github.com/helm/charts/pull/21174

**Pull request merged**
