### PR TITLE
Introduced custom volume mounting for adding JARs to the classpath

### PR DESCRIPTION
**Pull request by eminn**

### CODE REVIEW

**Comment by mesutcelik** [comment]
Is this fixing this issue?
https://github.com/hazelcast/charts/issues/18

Is there any easier way to upload jars to custom volume than the way explained in this [comment](https://github.com/hazelcast/charts/issues/18#issuecomment-568139776)?

I think initContainer is another option so we close #18 then we need to create another issue for initContainer.

**Comment by eminn** [comment]
This complements the story since you can mount a volume but it's not appended to the classpath. Haven't checked out the solution with initContainers so it needs to be investigated.

**Comment by eminn** [comment]
verify

**Comment by eminn** [comment]
verify

**Pull request merged**
