### PR TITLE
Multiple Host Ports

### PR DESCRIPTION
**Pull request by leszko**
Adds option for defining the custom part of `ports` section for the Hazelcast container. It can useful if you plan to use Hazelcast Advanced configuration and you want to expose multiple ports (e.g. one for client communication and one for WAN replication).

@huseyinbabal Please check if it solves Hazelcast Cloud issue with WAN Replication
@eminn Think if it would also make sense to Jet

### CODE REVIEW

**Comment by huseyinbabal** [comment]
@leszko can we proceed with back porting this to 3.12.x ?

**Comment by leszko** [comment]
@huseyinbabal yes, but please first check if it solves your problem and, if yes, then please approve this PR.

**Comment by mesutcelik** [comment]
@huseyinbabal @leszko Are we going to merge this?

**Comment by leszko** [comment]
@huseyinbabal do you still want it backported to 3.12.x?

**Pull request merged**
