### PR TITLE
add extraDeploy to values.yaml to deploy arbitrary additional resources

### PR DESCRIPTION
**Pull request by jouve**
inspired from bitnami charts  : 
* https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml#L39
* https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/extra-list.yaml

this allow us to deploy additional resources in the helm context  of the chart (same values, etc)

### CODE REVIEW

**Comment by semihbkgr** [comment]
Hi @jouve, Thanks for the PR.

**Comment by itscaro** [comment]
LGTM too

**Review by hasancelik — APPROVED** [review]

**Comment by jouve** [comment]
any things I can do to progress on this PR ?

**Comment by mtyazici** [comment]
@jouve, sorry for the delayed merge and thank you for the contribution!

**Pull request merged**
