### PR TITLE
Fix old value in readme

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/hazelcast/charts/111)

### CODE REVIEW

**Comment by leszko** [comment]
Duplicate of #110 ?

**Comment by davidkarlsen** [comment]
same issue - another file

**Comment by leszko** [comment]
Looks like they're both about the same file: `stable/hazelcast/README.adoc`. Isn't that the case?

**Comment by davidkarlsen** [comment]
doh - I might have missed something

**Pull request closed without merging**
