### PR TITLE
change description to service.name

### PR DESCRIPTION
**Pull request by andrey-gava**
Related to #211

### CODE REVIEW

**Comment by leszko** [comment]
@andrey-gava could you please sign CLA?

**Comment by hasancelik** [comment]
Hey @andrey-gava, it seems you have already signed the CLA but I think the problem is above commits comes from two different git users. One of the accounts which is `ahava` is not GH user. The possible solution is to squash the commits and push it forcefully to the PR via using `andrey-gava` user. cc: @leszko

**Comment by andrey-gava** [comment]
> Hey @andrey-gava, it seems you have already signed the CLA but I think the problem is above commits comes from two different git users. One of the accounts which is `ahava` is not GH user. The possible solution is to squash the commits and push it forcefully to the PR via using `andrey-gava` user. cc: @leszko

Thanks for help. I squash the commits, and open new fixed PR. I think this one can be closed.

**Comment by leszko** [comment]
duplicate of #213

**Pull request closed without merging**
